### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by Jiangdaoyin** [Athlici/Packing#1]
Hi Athlici,
Your Packing is really good,i want to run in my machine,when i run the makefile,i got sume error,like this:

g++ -std=c++1z -Ofast -lipopt -o packer tinyxml2.o main.o
/usr/bin/ld: main.o: in function `main':
main.cpp:(.text.startup+0x6d): undefined reference to `IpoptApplicationFactory'
collect2: error: ld returned 1 exit status
make: *** [Makefile:4: release] Error 1

This is my first time running a linux project，so i can't solve this error.
Do you know what caused this?

**Comment by Athlici** [comment]
Hi,

thank you for your interest in the project.
First of all, I would like to warn you that this is basically a Proof of Concept at this point and doesn't even always run stably on my own machine. So depending on what you want to do you might be better served by one of the other projects linked in the README.

The error occurs because the project needs the third party software/library IPOPT to be installed and available and the compiler is unable to find it.  So depending on which linux distro you are using this might be as easily fixed as installing an additional package and potentially making a small change to the Makefile.
So could you please tell me which linux distribution you are using and whether you have already tried to install IPOPT?

**Comment by Jiangdaoyin** [comment]
Thank you for your reply，my linux distro is Ubuntu,and my machine is also installed Ipopt.I referred to this method(https://github.com/casadi/casadi/wiki/InstallationLinux) to install. I can see the “IpIpoptApplication.hpp” in the include folder.If the Makefile need to change,can you tell me how to modify？

**Comment by Athlici** [comment]
Did you choose option 1, the package, or option 2, compiling yourself?

In either case could you try adding
-I/path1/ -L/path2/
in the 4th line of the Makefile, between $(CXXFLAGS) and -lipopt and replace path1 with the path to the folder containing that IpIpoptApplication.hpp and path2 with the path to a folder containing libipopt.so or libipopt.a?
If this doesn't work I should be able to set up an Ubuntu instance tomorrow and test it for myself.

**Comment by Jiangdaoyin** [comment]
I choose option2.Now I don’t have a suitable machine to test, I will test it on Monday.Thank you very much , have a nice weekend!

**Comment by Jiangdaoyin** [comment]
Hi Athlici,

I can work this by add path to makefile,thank you!
