### ISSUE TITLE
Extending to support rectangular containers -- how much more work required? 

### ISSUE THREAD

**Issue by DustinWehr** [Athlici/Packing#2]
You mentioned in the readme, "For example the infrastructure to extend this to an intersection of ... half-spaces for the container... is either already partially present or can be added easily."

How could I help or motivate you?

**Comment by Athlici** [comment]
I'll look into it.
Optimistically I might be able to get it done this week.

**Comment by DustinWehr** [comment]
Cool. I should disclose that the application is just to solve a pesky open recreational math problem.

**Comment by Athlici** [comment]
So, I've looked into it a little and the formula part of the necessary code is mostly there already.
I don't really know how much effort the glue part and debugging will be, but I'm working on it.

**Comment by DustinWehr** [comment]
Cool. I think it will make your code useful to a lot more people.

For my application specifically (resolving an open problem that might well maximize (difficulty*statement_simplicity)**/importance** over all published math problems), I would prefer to be able to construct (possibly with significant work) from a solver's data structure a correctness certificate that can be checked by either a single custom much simpler program (which I would write) that uses arbitrary precision arithmetic, or multiple complex programs (e.g. computer algebra systems, or other solvers). Subject to those constraints, it is fine if checking the certificate takes longer than the solver's search. Want to collaborate and be immortalized? ;-)

I'm presently trying to make https://github.com/dreal suit my needs. Their v4 https://github.com/dreal/dreal4 solves all the instances I need very quickly, but unfortunately they haven't implemented the proof output feature that they had in v3, and I'm still trying to get v3 to run.

**Comment by Athlici** [comment]
First of, I haven't forgotten about this. I'm just a little swamped with work at the moment, so, despite my initial optimism, it might take a while. I actually put the code out here to gauge whether it might be useful to anyone at all; to decide if it's worth the time to improve/polish and I believe this has been answered positively, to a certain degree.
Just a side note, maximizing that formula you are minimizing importance, right ;)
I don't have much formal verification experience, but I'd imagine that for polygons it's doable, although difficult because it seems to me like you'd need to reimplement all these concepts, like convexity, minkowski sum/distance between them. For the quadratic shapes you'd either have to define a lot of things as given or verifiy/implement a non neglibible part of real algebraic geometry. Keep in mind that I have no idea how good the libraries for all of this are.

**Comment by DustinWehr** [comment]
Minimizing importance, yes. The problem is: What is the smallest square that can pack two unit circles, one of which is split into two pieces by a chord? It's harder than it seems. I completed a proof just yesterday that uses dReal (with the incircle trick from QP-Nest) and z3 for some parts. Just last night managed to get the old dReal3's proof output feature working after finding a baffling closed "wontfix"-tagged issue that explains why all my instances were causing seg faults. 

I'd definitely use your code to provide independent validation of the result.

**Comment by DustinWehr** [comment]
I didn't mean that I was attempting to do a formal proof from some minimal axiomatic system (like what was eventually done for the kepler conjecture), so defining a lot of things as given is fine. I want reasonable people, not pedants, to be convinced the result is true.

**Comment by DustinWehr** [comment]
I think I remember reading in a phi functions paper that specifying lower bounds on the distances between objects was supported. If that and upper bounds were both possible, I could imagine your library being used to improve some constraint-based drawing project.

**Comment by Athlici** [comment]
So, it took two months but I finally got around to looking into the code.
It turned out to actually be two very small but nefarious bugs; and I found a whole lot more (which I still have to fix) in the process.
The example you gave, circle and split circle unfortunately still doesn't work and I don't think my program will be useful to prove much, except for generating positive examples.
Regarding minimum and maximum distances between objects: That is indeed possible because the primitives that are used essentially calculate the euclidean norm and so for those it's just an offset and a naive implementation would probably work. However this would miss some possible configurations because the geometry gets more complicated and only the sign of the PhiFunctions is currently exact.
So for some objects A and B, what one really wants instead of Phi(A,B)>=r is Phi(A+rC,B)>=0 where A+rC is meant to be the Minkowski sum of A with a circle of radius r. The shapes the program uses are closed under this operation (a polygon for example becoming a union of a polygon and circles) and I believe this kind of decomposition would be the easiest way of implementing it, but for now I didn't want to deal with the case distinctions and all.
Anyways, the program can now do this:
![square](https://user-images.githubusercontent.com/815027/117733243-82863400-b1f1-11eb-9bbb-b00244ac0dcf.png)

**Comment by Athlici** [comment]
So, the reason why I couldn't make your example work is because I forgot that the circle segments only support <180° and for everything else unions are needed. Not particularly elegant, but that's how it's implemented at the moment.
I also found a bug in visualization code in the process, relating to circle segments. Finally, here you go:
![image](https://user-images.githubusercontent.com/815027/119586701-85764c80-bdcd-11eb-8359-c66b4feb1e37.png)
